version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/chamchimayo
    overwrite: yes

permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    # location은 프로젝트의 root경로를 기준
    - location: scripts/deploy.sh
      timeout: 60
      runas: root