spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://db-9a75i.pub-cdb.ntruss.com:3306/chamchimayo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: user
    password: Samkim2!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace