spring:
  profiles:
    include: oauth
  # 데이터 소스 설정
  datasource:
    url: jdbc:mysql://db-9a75i.pub-cdb.ntruss.com:3306/chamchimayo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: Samkim2!
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jackson:
  #    property-naming-strategy: SNAKE_CASE

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
    database: mysql

logging:
  level:
    org:
      hibernate :
        SQL : info