spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/slub?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace