spring:
  profiles:
    include: aws
  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/slub?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

cloud:
  aws:
    s3:
      bucket: image-upload-test-2
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace